version: '2'
services:
  nginx:
    image: "yupe-nginx:1.2"
    restart: always
    depends_on:
      - php
    links:
      - php
    build:
      context: "./docker/source/nginx/dev"
      dockerfile: "./Dockerfile"
    volumes:
      - "./app:/app"
      - "./docker/source/nginx/dev/conf.d:/etc/nginx/conf.d:ro"
      - "./docker/logs/dev:/var/log/nginx"
    expose:
      - "80"
    ports:
      - "7771:80"
    environment:
      VIRTUAL_HOST: "yupe.local"
      APP_ENV: "dev"
    networks:
      - web
    labels:
      - "traefik.backend=nginx"
      - "traefik.frontend.rule=Host:yupe.local"
  db:
    image: "yupe-db-dev:1.2"
    restart: always
    build:
      context: "./docker/source/mariadb/dev"
      dockerfile: "./Dockerfile"
    volumes:
      - "db_data:/var/lib/mysql"
      - "./docker/source/mariadb/db_dump/db_yupe:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_USER: "yupe"
      MYSQL_DATABASE: "db_yupe"
      MYSQL_PASSWORD: "123"
    networks:
      - web
    labels:
      - "traefik.backend=db"
  php:
    image: "yupe-php-dev:1.2"
    build:
      context: "./docker/source/php/dev"
      dockerfile: "./Dockerfile"
    restart: always
    links:
      - redis:cache
      - db:db
    depends_on:
      - redis
      - db
    volumes:
      - "./app:/app"
    env_file:
      - "./docker/env/dev/XDEBUG_CONFIG.env"
    environment:
      PHP_IDE_CONFIG: "serverName=yupe.local"
      APP_ENV: "dev"
    networks:
      - web
    labels:
      - "traefik.backend=php"
  redis:
    image: "yupe-redis:1.2"
    build:
      context: "./docker/source/redis"
      dockerfile: "./Dockerfile"
    restart: always
    networks:
      - web
    labels:
      - "traefik.backend=redis"
volumes:
  db_data:
    external: false
networks:
  web:
    external:
      name: traefik_webgateway