version: '2'
services:
  nginx:
    build:
      context: ./
      dockerfile: "./docker/source/nginx/dev/Dockerfile"
    volumes:
      - "./app/yupe:/app"
      - "./docker/source/nginx/dev/conf.d:/etc/nginx/conf.d:ro"
      - "./docker/logs/dev:/var/log/nginx"
    expose:
      - "80"
    ports:
      - "${EXTERNAL_WEB_DEV_PORT}:80"
    env_file:
      - "./docker/env/dev/VIRTUAL_HOST.env"
      - "./docker/env/dev/APP_ENV.env"
  db:
    build:
      context: ./
      dockerfile: "./docker/source/mariadb/dev/Dockerfile"
    volumes:
      - "db_data:/var/lib/mysql"
      - "./docker/source/mariadb/db_dump/db_yupe:/docker-entrypoint-initdb.d"
    env_file:
      - "./docker/env/dev/db.env"
  php:
    image: "${APP_NAME}-php-dev:${TAG}"
    build:
      context: ./
      dockerfile: "./docker/source/php/dev/Dockerfile"
    volumes:
      - "./app/yupe:/app"
      - "./docker/source/php/dev/app/protected/config:/app/protected/config:rw"
    env_file:
      - "./docker/env/dev/XDEBUG_CONFIG.env"
      - "./docker/env/dev/PHP_IDE_CONFIG.env"
      - "./docker/env/dev/APP_ENV.env"
  adminer:
    build:
      context: ./
      dockerfile: "./docker/source/adminer/Dockerfile"
    ports:
      - "${EXTERNAL_ADMINER_DEV_PORT}:80"
volumes:
  db_data:
    external: false
