version: "3"
services:

  nginx:
    image: "yupe-nginx:1.17"
    restart: always
    depends_on:
      - php
    build:
      context: "./docker/source/nginx/dev"
      dockerfile: "./Dockerfile"
    volumes:
      - "./app:/var/www/app:rw"
      - "./docker/source/nginx/dev/conf.d:/etc/nginx/conf.d:ro"
      - "./docker/logs/dev:/var/log/nginx"
    expose:
      - "80"
    ports:
      - "7771:80"
    environment:
      VIRTUAL_HOST: "yupe.loc"
      APP_ENV: "dev"
    networks:
      - traefik
    labels:
      - "traefik.frontend.rule=Host:yupe.loc"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.backend=yupe-nginx"
      - "traefik.docker.network=traefik"
      - "traefik.frontend.passHostHeader=true"

  db:
    image: "yupe-db:10.4"
    restart: always
    build:
      context: "./docker/source/mariadb/dev"
      dockerfile: "./Dockerfile"
    volumes:
      - "db_data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_USER: "yupe"
      MYSQL_DATABASE: "db_yupe"
      MYSQL_PASSWORD: "123"
    networks:
      - traefik
    labels:
      - "traefik.backend=yupe-db"
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

  php:
    image: "yupe-php-dev:7.0-fpm"
    build:
      context: "./docker/source/php/dev"
      dockerfile: "./Dockerfile"
      args:
        USER: "${USER}"
    restart: always
    hostname: "yupe.loc"
    depends_on:
      - redis
      - db
    volumes:
      - "./app:/var/www/app:rw"
      - "yupe-composer:/var/www/.composer"
    environment:
      PHP_IDE_CONFIG: "serverName=yupe.loc"
      XDEBUG_CONFIG: "remote_host=172.17.0.1"
      APP_ENV: "dev"
      YII_TRACE_LEVEL: 3
      YII_DEBUG: 1
    networks:
      - traefik
    user: "${USER}"
    labels:
      - "traefik.backend=yupe-php"
      - "traefik.enable=true"
      - "traefik.port=9000"
      - "traefik.docker.network=traefik"
    working_dir: "/var/www/app/yupe"
  redis:
    image: "redis:5.0"
    restart: always
    networks:
      - traefik
    labels:
      - "traefik.backend=yupe-redis"
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

volumes:
  db_data:
    external: false
  yupe-composer:
    external: false

networks:
  traefik:
    external: true
