version: '3'
services:

  nginx:
    image: "yupe-nginx:1.17"
    restart: always
    depends_on:
      - php
    build:
      context: "./docker/source/nginx/prod"
      dockerfile: "./Dockerfile"
    volumes:
      - "./app:/var/www/app:rw"
      - "./docker/source/nginx/prod/conf.d:/etc/nginx/conf.d:ro"
      - "./docker/logs/prod:/var/log/nginx"
    expose:
      - "80"
    ports:
      - "7781:80"
    environment:
      VIRTUAL_HOST: "yupe.loc"
      APP_ENV: "prod"
    networks:
      - traefik
    labels:
      - "traefik.frontend.rule=Host:yupe.loc"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.docker.network=traefik"
      - "traefik.backend=yupe-nginx"
      - "traefik.frontend.passHostHeader=true"

  db:
    image: "yupe-db:10.4"
    restart: always
    build:
      context: "./docker/source/mariadb/prod"
      dockerfile: "./Dockerfile"
    volumes:
      - "db_data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_USER: "yupe"
      MYSQL_DATABASE: "db_yupe"
      MYSQL_PASSWORD: "123"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.backend=yupe-db"

  php:
    image: "yupe-php:7.0-fpm"
    build:
      context: "./docker/source/php/prod"
      dockerfile: "./Dockerfile"
      args:
        USER: "${USER}"
    restart: always
    hostname: "yupe.loc"
    depends_on:
      - redis
      - db
    volumes:
      - "./app:/var/www/app:rw"
      - "yupe-composer:/var/www/.composer"
    environment:
      APP_ENV: "prod"
      YII_TRACE_LEVEL: 0
      YII_DEBUG: 0
    networks:
      - traefik
    labels:
      - "traefik.backend=yupe-php"
      - "traefik.enable=true"
      - "traefik.port=9000"
      - "traefik.docker.network=traefik"
    working_dir: "/var/www/app/yupe"

  redis:
    image: "redis:5.0"
    restart: always
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.backend=yupe-redis"

volumes:
  db_data:
    external: false
  yupe-composer:
    external: false


networks:
  traefik:
    external: true