version: '3'
services:

  nginx:
    image: "yupe-nginx:1.17"
    restart: always
    depends_on:
      - php
    build:
      context: "./docker/source/nginx/prod"
      dockerfile: "./Dockerfile"
    volumes:
      - "./app:/app"
      - "./docker/source/nginx/prod/conf.d:/etc/nginx/conf.d:ro"
      - "./docker/logs/prod:/var/log/nginx"
    expose:
      - "80"
    ports:
      - "7781:80"
    environment:
      VIRTUAL_HOST: "yupe.loc"
      APP_ENV: "prod"
    networks:
      - traefik
    labels:
      - "traefik.frontend.rule=Host:yupe.loc"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.docker.network=traefik"
      - "traefik.frontend.passHostHeader=true"

  db:
    image: "yupe-db:1.17.4"
    restart: always
    build:
      context: "./docker/source/mariadb/prod"
      dockerfile: "./Dockerfile"
    volumes:
      - "db_data:/var/lib/mysql"
      - "./docker/source/mariadb/db_dump/db_yupe:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_USER: "yupe"
      MYSQL_DATABASE: "db_yupe"
      MYSQL_PASSWORD: "123"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

  php:
    image: "yupe-php:7.0-fpm"
    build:
      context: "./docker/source/php/prod"
      dockerfile: "./Dockerfile"
    restart: always
    links:
      - redis:cache
      - db:db
    depends_on:
      - redis
      - db
    volumes:
      - "./app:/app"
    environment:
      APP_ENV: "prod"
      YII_TRACE_LEVEL: 0
      YII_DEBUG: 0
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.port=9000"
      - "traefik.docker.network=traefik"

  redis:
    image: "redis:5.0"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

volumes:
  db_data:
    external: false

networks:
  traefik:
    external: true