version: '2'
services:
  nginx:
    build:
      context: ./
      dockerfile: ./docker/source/nginx/test/Dockerfile
    volumes:
      - "./app/yupe:/app"
      - "./docker/source/nginx/test/conf.d:/etc/nginx/conf.d:ro"
      - ./docker/logs/test:/var/log/nginx
    expose:
      - 80
    env_file:
      - "./docker/env/test/VIRTUAL_HOST.env"
      - "./docker/env/test/APP_ENV.env"
  db:
    build:
      context: ./
      dockerfile: ./docker/source/mariadb/test/Dockerfile
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/source/mariadb/db_dump/db_yupe:/docker-entrypoint-initdb.d
    env_file:
      - ./docker/env/test/db.env
  php:
    build:
      context: ./
      dockerfile: ./docker/source/php/test/Dockerfile
    volumes:
      - "./app/yupe:/app"
      - ./docker/source/php/test/app/protected/config:/app/protected/config:rw
    env_file:
      - "./docker/env/test/XDEBUG_CONFIG.env"
      - "./docker/env/test/PHP_IDE_CONFIG.env"
      - "./docker/env/test/APP_ENV.env"
  composer:
    build:
      context: ./
      dockerfile: ./docker/source/composer/test/Dockerfile
    command: update --prefer-dist
    volumes:
      - "./app/yupe:/app"
  adminer:
    build:
      context: ./
      dockerfile: ./docker/source/adminer/Dockerfile
    ports:
      - "${EXTERNAL_ADMINER_TEST_PORT}:80"
volumes:
  db_data:
    external: false
